import type { Metadata } from "next";
import "./globals.css";
import Nav from "./shared/nav";
import Footer from "./shared/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen flex flex-col`}>
        <header>
          <Nav />
        </header>

        <main className="h-full">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
